### ISSUE TITLE
status code 429

### ISSUE THREAD

**Issue by c1h4n61r** [alperssl/InstagramBlack#2]
background.js:1572 GET https://www.instagram.com/graphql/query/?query_hash=24a36f49b32dea22e33c2e6e35bad4d3&variables=%7B%22only_stories%22%3Atrue%2C%22stories_prefetch%22%3Afalse%2C%22stories_video_dash_manifest%22%3Afalse%7D 429
check @ background.js:1572
autoCheck @ background.js:1187
(anonymous) @ background.js:1165
background.js:1572 GET https://www.instagram.com/graphql/query/?query_hash=24a36f49b32dea22e33c2e6e35bad4d3&variables=%7B%22only_stories%22%3Atrue%2C%22stories_prefetch%22%3Afalse%2C%22stories_video_dash_manifest%22%3Afalse%7D 429
check @ background.js:1572
autoCheck @ background.js:1187
(anonymous) @ background.js:1197
setInterval (async)
(anonymous) @ background.js:1196
background.js:1572 GET https://www.instagram.com/graphql/query/?query_hash=24a36f49b32dea22e33c2e6e35bad4d3&variables=%7B%22only_stories%22%3Atrue%2C%22stories_prefetch%22%3Afalse%2C%22stories_video_dash_manifest%22%3Afalse%7D 429
check @ background.js:1572
autoCheck @ background.js:1187
(anonymous) @ background.js:1197
setInterval (async)
(anonymous) @ background.js:1196
background.js:1572 GET https://www.instagram.com/graphql/query/?query_hash=24a36f49b32dea22e33c2e6e35bad4d3&variables=%7B%22only_stories%22%3Atrue%2C%22stories_prefetch%22%3Afalse%2C%22stories_video_dash_manifest%22%3Afalse%7D 429

**Comment by alperssl** [comment]
Did you try increasing Autosaver Interval ?

**Comment by c1h4n61r** [comment]
> Did you try increasing Autosaver Interval ?
![image](https://user-images.githubusercontent.com/9366965/107138841-ffbab800-6927-11eb-8931-0155d5700d90.png)

**Comment by c1h4n61r** [comment]
![image](https://user-images.githubusercontent.com/9366965/107143610-00167b80-6947-11eb-81b3-ed144e27faa5.png)

**Comment by alperssl** [comment]
you have to be following the people you add to watchlist.

**Comment by c1h4n61r** [comment]
yes, the people I follow. The list is long. 200 people are on the list. It starts working after a certain period of time. after that. I saw you download the same story records again.

**Comment by alperssl** [comment]
It's not build for that long list actually, it seems that is the reason you got 429 code. Instagram is not providing official APIs for that kind of applications and I'm using just the same query method of web app of instagram. About downloading same records;
There is no way to get records after any update so it is getting all data on interval time and checking it, if it has any update, sending message to your Telegram chat and/or downloading these updates.

**Comment by c1h4n61r** [comment]
If a time interval is put in the query part or in the consecutive download part, do you think this problem will be corrected?

**Comment by alperssl** [comment]
First of all IMO it's not possible to query 200 accounts with this query method or even if it's possible probably your account will be disabled by Instagram due to suspicious activity.
